### ISSUE TITLE
The source of the scripts 

### ISSUE THREAD

**Issue by hmyh1202** [JunyueC/sci-fate_analysis#1]
Hello:
    Does the scripts has corresponding published paper or theoretical support that you can share?
Thanks

**Comment by JunyueC** [comment]
Thanks for your interest! The script is linked to our unpublished manuscript in bioRxiv: https://www.biorxiv.org/content/10.1101/666081v1.abstract <https://www.biorxiv.org/content/10.1101/666081v1.abstract>

Jun

**Comment by hmyh1202** [comment]
Than you!
